import { query } from './db';

export type CatalogModelStock = { model: string; listings: number; units: number; value: number };
export type CatalogStockSummary = { models: CatalogModelStock[]; listings: number; units: number; value: number };
/** Filters are generated by the catalog page; totals cover every result, not its current page. */
export const catalogStockSummary = async (where: string, values: unknown[]): Promise<CatalogStockSummary> => {
  const rows = (await query(String.raw`
    WITH offers AS (
      SELECT lower(coalesce(brand,'')) AS brand_key,
        coalesce(nullif(btrim(model),''),title) AS model_name,brand,
        greatest(coalesce(stock,0),0) AS units,
        CASE WHEN jsonb_typeof(variants)='array' THEN CASE WHEN jsonb_array_length(variants)>0 THEN
          coalesce((SELECT sum(
            CASE WHEN coalesce(v->>'stock','') ~ '^\d+$' THEN (v->>'stock')::numeric ELSE 0 END *
            CASE WHEN coalesce(v->>'price','') ~ '^\d+(\.\d+)?$' THEN (v->>'price')::numeric ELSE price END
          ) FROM jsonb_array_elements(variants) v),0)
        ELSE greatest(coalesce(stock,0),0)*price END ELSE greatest(coalesce(stock,0),0)*price END AS value
      FROM products ${where}
    ), normalized AS (
      SELECT brand_key,units,value,
        CASE WHEN lower(model_name) LIKE lower(brand)||' %' THEN btrim(substr(model_name,length(brand)+1)) ELSE model_name END AS model_name
      FROM offers
    )
    SELECT min(model_name) AS model,count(*)::int AS listings,sum(units) AS units,sum(value) AS value
    FROM normalized GROUP BY brand_key,lower(regexp_replace(model_name,'\s+',' ','g'))
    ORDER BY units DESC,model ASC`, values)).rows;
  const models = rows.map(row => ({ model: String(row.model), listings: Number(row.listings), units: Number(row.units), value: Number(row.value) }));
  return { models, listings: models.reduce((n,m) => n+m.listings,0), units: models.reduce((n,m) => n+m.units,0), value: models.reduce((n,m) => n+m.value,0) };
};
