export type CouponCampaign={id:string;code:string;discountType:"percent"|"fixed";discountValue:number;minimumOrderCents:number;eligibleProductIds:string[];eligibleCategories:string[];startsAt:string|null;endsAt:string|null;maximumRedemptions:number|null;redemptionCount:number;isActive:boolean};
export type CouponCart={subtotalAmountCents:number;items:Array<{productId:string;category:string;lineAmountCents:number}>};
export type CouponResult={ok:true;eligibleSubtotalCents:number;discountAmountCents:number;code:string;campaignId:string}|{ok:false;error:"inactive"|"not_started"|"expired"|"limit_reached"|"minimum_not_met"|"not_eligible"|"invalid"};
export type CampaignAdminInput={id?:string;code?:string;title?:{de?:string;en?:string};description?:{de?:string;en?:string};discountType?:string;discountValue?:number;minimumOrder?:number;eligibleProductIds?:string[];eligibleCategories?:string[];startsAt?:string|null;endsAt?:string|null;maximumRedemptions?:number|null;isActive?:boolean};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const categories=new Set(["smartphones","tablets","laptops","accessories","consoles"]);const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
export const sanitizeCampaignInput=(input:CampaignAdminInput)=>{const code=clean(input.code,64).toUpperCase();if(!/^[A-Z0-9][A-Z0-9_-]{2,63}$/.test(code))throw new Error("invalid_code");const discountType=input.discountType==="fixed"?"fixed":"percent";const discountValue=Number(input.discountValue);if(!Number.isFinite(discountValue)||discountValue<=0||(discountType==="percent"&&discountValue>100))throw new Error("invalid_discount");const minimumOrder=Math.max(0,Number(input.minimumOrder)||0);const maximumRedemptions=input.maximumRedemptions==null?null:Math.max(1,Math.floor(Number(input.maximumRedemptions)));const startsAt=input.startsAt?new Date(input.startsAt).toISOString():null;const endsAt=input.endsAt?new Date(input.endsAt).toISOString():null;if(startsAt&&endsAt&&endsAt<=startsAt)throw new Error("invalid_window");return{id:uuid.test(input.id??"")?input.id:undefined,code,title:{de:clean(input.title?.de,160),en:clean(input.title?.en,160)},description:{de:clean(input.description?.de,500),en:clean(input.description?.en,500)},discountType,discountValue,minimumOrder,eligibleProductIds:Array.from(new Set((input.eligibleProductIds??[]).filter(id=>uuid.test(id)))).slice(0,250),eligibleCategories:Array.from(new Set((input.eligibleCategories??[]).filter(category=>categories.has(category)))).slice(0,10),startsAt,endsAt,maximumRedemptions,isActive:input.isActive===true};};
export const getCampaignRemovalMode = (hasRedemptionHistory: boolean): "delete" | "archive" => hasRedemptionHistory ? "archive" : "delete";
export const canReserveCampaignRedemption = (maximumRedemptions: number | null, activeCount: number, alreadyReserved: boolean): boolean => alreadyReserved || maximumRedemptions === null || activeCount < maximumRedemptions;
export const resolveOptionalAvailability = async (loader: () => Promise<boolean>): Promise<boolean> => { try { return await loader(); } catch { return false; } };

export const applyCouponToTotals=(cart:{subtotalAmountCents:number;shippingAmountCents:number;vatRate:number},coupon:{campaignId:string;code:string;discountAmountCents:number})=>{const discountAmountCents=Math.min(Math.max(0,Math.round(coupon.discountAmountCents)),Math.max(0,Math.round(cart.subtotalAmountCents)));const discountedSubtotalAmountCents=Math.max(0,Math.round(cart.subtotalAmountCents)-discountAmountCents);const shippingAmountCents=Math.max(0,Math.round(cart.shippingAmountCents));const totalAmountCents=discountedSubtotalAmountCents+shippingAmountCents;const vatAmountCents=Math.round(totalAmountCents-totalAmountCents/(1+cart.vatRate));return{campaignId:coupon.campaignId,couponCode:coupon.code,originalSubtotalAmountCents:Math.round(cart.subtotalAmountCents),discountAmountCents,discountedSubtotalAmountCents,shippingAmountCents,totalAmountCents,vatAmountCents};};
export const calculateCampaignDiscount=(campaign:CouponCampaign,cart:CouponCart,now=new Date()):CouponResult=>{if(!campaign.isActive)return{ok:false,error:"inactive"};if(!Number.isFinite(campaign.discountValue)||campaign.discountValue<=0)return{ok:false,error:"invalid"};const starts=campaign.startsAt?new Date(campaign.startsAt):null;const ends=campaign.endsAt?new Date(campaign.endsAt):null;if(starts&&(!Number.isFinite(starts.getTime())||now<starts))return{ok:false,error:"not_started"};if(ends&&(!Number.isFinite(ends.getTime())||now>=ends))return{ok:false,error:"expired"};if(campaign.maximumRedemptions!==null&&campaign.redemptionCount>=campaign.maximumRedemptions)return{ok:false,error:"limit_reached"};if(cart.subtotalAmountCents<campaign.minimumOrderCents)return{ok:false,error:"minimum_not_met"};const allEligible=campaign.eligibleProductIds.length===0&&campaign.eligibleCategories.length===0;const eligible=cart.items.filter(item=>allEligible||campaign.eligibleProductIds.includes(item.productId)||campaign.eligibleCategories.includes(item.category));const eligibleSubtotalCents=eligible.reduce((sum,item)=>sum+Math.max(0,Math.round(item.lineAmountCents)),0);if(eligibleSubtotalCents<=0)return{ok:false,error:"not_eligible"};const raw=campaign.discountType==="percent"?Math.round(eligibleSubtotalCents*Math.min(100,campaign.discountValue)/100):Math.round(campaign.discountValue);const discountAmountCents=Math.min(eligibleSubtotalCents,Math.max(0,raw));if(discountAmountCents<=0)return{ok:false,error:"invalid"};return{ok:true,eligibleSubtotalCents,discountAmountCents,code:campaign.code,campaignId:campaign.id};};
